# Generated by Django 4.0.2 on 2022-02-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_veggies_veggie_rename_veggies_pizza_veggie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='Crust',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='base',
            new_name='crust',
        ),
    ]
