# Generated by Django 4.0.2 on 2022-02-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cheese_image_crust_image_sauce_image_veggie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese',
            name='image',
        ),
        migrations.RemoveField(
            model_name='crust',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='image',
        ),
        migrations.RemoveField(
            model_name='veggie',
            name='image',
        ),
    ]
