# Generated by Django 4.0.2 on 2022-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
