export const PIZZA_LIST_REQUEST = "PIZZA_LIST_REQUEST";
export const PIZZA_LIST_SUCCESS = "PIZZA_LIST_SUCCESS";
export const PIZZA_LIST_FAIL = "PIZZA_LIST_FAIL";

export const PIZZA_INGREDIENTS_REQUEST = "PIZZA_INGREDIENTS_REQUEST";
export const PIZZA_INGREDIENTS_SUCCESS = "PIZZA_INGREDIENTS_SUCCESS";
export const PIZZA_INGREDIENTS_FAIL = "PIZZA_INGREDIENTS_FAIL";

export const MAKE_PIZZA_REQUEST = "MAKE_PIZZA_REQUEST";
export const MAKE_PIZZA_SUCCESS = "MAKE_PIZZA_SUCCESS";
export const MAKE_PIZZA_FAIL = "MAKE_PIZZA_FAIL";
export const MAKE_PIZZA_RESET = "MAKE_PIZZA_RESET";

export const GET_PIZZA_REQUEST = "GET_PIZZA_REQUEST";
export const GET_PIZZA_SUCCESS = "GET_PIZZA_SUCCESS";
export const GET_PIZZA_FAIL = "GET_PIZZA_FAIL";

export const CREATE_PIZZA_REVIEW_REQUEST = "CREATE_PIZZA_REVIEW_REQUEST";
export const CREATE_PIZZA_REVIEW_SUCCESS = "CREATE_PIZZA_REVIEW_SUCCESS";
export const CREATE_PIZZA_REVIEW_FAIL = "CREATE_PIZZA_REVIEW_FAIL";
export const CREATE_PIZZA_REVIEW_RESET = "CREATE_PIZZA_REVIEW_RESET";

export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_CLEAR_ITEMS = "BASKET_CLEAR_ITEMS";

export const BASKET_SAVE_SHIPPING_ADDRESS = "BASKET_SAVE_SHIPPING_ADDRESS";
export const BASKET_SAVE_PAYMENT_METHOD = "BASKET_SAVE_PAYMENT_METHOD";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const CHANGE_ORDER_STATUS_REQUEST = "CHANGE_ORDER_STATUS_REQUEST";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export const CHANGE_ORDER_STATUS_FAIL = "CHANGE_ORDER_STATUS_FAIL";
export const CHANGE_ORDER_STATUS_RESET = "CHANGE_ORDER_STATUS_RESET";
